repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: 37d3055fece566105cf8cff7c17b7b2355a01677  # frozen: v1.14.2
    hooks:
      - id: helm-docs-built
        alias: helm-docs
        args:
          # Make the tool search for charts only under the `charts/terrateam` directory
          - --chart-search-root=charts/terrateam

          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
